name       : python-jaraco.classes
version    : 3.2.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/bf/02/a956c9bfd2dfe60b30c065ed8e28df7fcf72b292b861dca97e951c145ef6/jaraco.classes-3.2.3.tar.gz : 89559fa5c1d3c34eff6f631ad80bb21f378dbcbb35dd161fd2c6b93f5be2f98a
homepage   : https://github.com/jaraco/jaraco.classes
license    : MIT
component  : programming.python
summary    : Utility functions for Python class constructs
description: |
    Utility functions for Python class constructs
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-more-itertools
build      : |
    %python3_setup
install    : |
    %python3_install
